<?php
$titulo_pagina='Mensagens';$estilos_pagina=['/assets/css/chat.css?v=1'];$scripts_pagina=['/assets/js/chat.js?v=1'];require_once __DIR__.'/includes/auth.php';require_once __DIR__.'/includes/functions.php';verificarAutenticacao();
$usuario_id=(int)$_SESSION['usuario_id'];
if(isset($_GET['profissional_id'])){$profissional_id=(int)$_GET['profissional_id'];$perfil=pegar_perfil_profissional($profissional_id);if(!$perfil){mensagem_erro('Profissional indisponível.');redirecionar('/profissionais.php');}if((int)$perfil['usuario_id']===$usuario_id){mensagem_erro('Você não pode iniciar uma conversa consigo mesmo.');redirecionar('/dashboard/');}$stmt=$mysqli->prepare('INSERT INTO conversas(cliente_id,profissional_id) VALUES(?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),atualizado_em=atualizado_em');$stmt->bind_param('ii',$usuario_id,$profissional_id);$stmt->execute();$conversa_id=(int)$mysqli->insert_id;redirecionar('/chat.php?conversa='.$conversa_id);}
$sql='SELECT c.id,c.atualizado_em,c.cliente_id,p.usuario_id profissional_usuario_id,u_cliente.nome cliente_nome,u_prof.nome profissional_nome,p.titulo_profissional,(SELECT mensagem FROM mensagens WHERE conversa_id=c.id ORDER BY id DESC LIMIT 1) ultima_mensagem,(SELECT COUNT(*) FROM mensagens WHERE conversa_id=c.id AND remetente_id<>? AND lida=0) nao_lidas FROM conversas c JOIN profissionais p ON p.id=c.profissional_id JOIN usuarios u_cliente ON u_cliente.id=c.cliente_id JOIN usuarios u_prof ON u_prof.id=p.usuario_id WHERE c.cliente_id=? OR p.usuario_id=? ORDER BY c.atualizado_em DESC';$stmt=$mysqli->prepare($sql);$stmt->bind_param('iii',$usuario_id,$usuario_id,$usuario_id);$stmt->execute();$conversas=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$conversa_id=(int)($_GET['conversa']??($conversas[0]['id']??0));$conversa=$conversa_id?pegar_conversa_autorizada($conversa_id,$usuario_id):null;if($conversa_id&&!$conversa){http_response_code(403);$conversa_id=0;}
require_once __DIR__.'/includes/header.php';
?>
<section class="chat-page"><div class="container"><header class="chat-heading"><span>CHAT VOLTX</span><h1>Suas conversas</h1><p>Combine detalhes do serviço diretamente pela plataforma.</p></header><div class="chat-layout <?php echo $conversa?'has-thread':''; ?>"><aside class="chat-sidebar"><div class="chat-sidebar-title"><strong>Mensagens</strong><a href="/profissionais.php">＋ Nova conversa</a></div><?php if($conversas): foreach($conversas as $item): $outro=(int)$item['profissional_usuario_id']===$usuario_id?$item['cliente_nome']:$item['profissional_nome']; ?><a class="chat-contact <?php echo (int)$item['id']===$conversa_id?'active':''; ?>" href="/chat.php?conversa=<?php echo (int)$item['id']; ?>"><span><?php echo sanitizar(mb_strtoupper(mb_substr($outro,0,1))); ?></span><div><strong><?php echo sanitizar($outro); ?></strong><small><?php echo sanitizar(mb_strimwidth($item['ultima_mensagem']?:$item['titulo_profissional'],0,45,'…')); ?></small></div><?php if($item['nao_lidas']): ?><b><?php echo (int)$item['nao_lidas']; ?></b><?php endif; ?></a><?php endforeach; else: ?><div class="chat-no-conversations"><span>◌</span><p>Você ainda não iniciou nenhuma conversa.</p><a href="/profissionais.php">Encontrar profissionais</a></div><?php endif; ?></aside><section class="chat-thread"><?php if($conversa): $outro=(int)$conversa['profissional_usuario_id']===$usuario_id?$conversa['cliente_nome']:$conversa['profissional_nome']; ?><header><div class="chat-avatar"><?php echo sanitizar(mb_strtoupper(mb_substr($outro,0,1))); ?></div><div><strong><?php echo sanitizar($outro); ?></strong><small><?php echo sanitizar($conversa['titulo_profissional']); ?></small></div></header><div class="chat-messages" id="chat-messages" data-conversation="<?php echo $conversa_id; ?>" data-user="<?php echo $usuario_id; ?>"><div class="chat-loading">Carregando mensagens…</div></div><form id="chat-form"><input type="hidden" name="conversa_id" value="<?php echo $conversa_id; ?>"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><label class="sr-only" for="chat-text">Mensagem</label><textarea id="chat-text" name="mensagem" rows="1" maxlength="2000" placeholder="Digite sua mensagem…" required></textarea><button type="submit" aria-label="Enviar mensagem">Enviar ↑</button></form><?php else: ?><div class="chat-placeholder"><span>✉</span><h2>Selecione uma conversa</h2><p>Ou encontre um profissional para começar.</p><a class="btn" href="/profissionais.php">Buscar profissionais</a></div><?php endif; ?></section></div></div></section><?php require_once __DIR__.'/includes/footer.php'; ?>
