<?php
$titulo_pagina = 'Home';
$estilos_pagina = ['/assets/css/feed.css?v=1'];
require_once __DIR__ . '/includes/functions.php';
$servicos_home = array_values(array_filter(pegar_servicos(), fn($servico) => empty($servico['pausado'])));
$total_profissionais = (int)($mysqli->query('SELECT COUNT(*) total FROM profissionais WHERE ativo=1')->fetch_assoc()['total'] ?? 0);
$whatsapp = preg_replace('/\D/', '', config_site('whatsapp', '5561981044986'));
if ($whatsapp && !str_starts_with($whatsapp, '55')) $whatsapp = '55' . $whatsapp;
$responsavel = config_site('responsavel', 'Equipe VoltX');
$regiao = config_site('regiao_atendimento', 'Distrito Federal e Entorno');
$horario = config_site('horario_atendimento', 'Seg–Sex, 8h às 18h');
$mensagem_whatsapp = rawurlencode('Olá ' . $responsavel . '! Vim pelo site da VoltX e gostaria de falar sobre um serviço elétrico.');
$recomendados=$mysqli->query('SELECT p.*,u.nome,COALESCE(AVG(a.nota),0) media,COUNT(DISTINCT a.id) avaliacoes FROM profissionais p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN avaliacoes_profissionais a ON a.profissional_id=p.id WHERE p.ativo=1 GROUP BY p.id ORDER BY p.verificado DESC,media DESC,p.atualizado_em DESC LIMIT 6')->fetch_all(MYSQLI_ASSOC);
$ranking=$mysqli->query('SELECT p.id,u.nome,p.titulo_profissional,p.cidade,p.uf,COALESCE(AVG(a.nota),0) media,COUNT(a.id) avaliacoes FROM profissionais p JOIN usuarios u ON u.id=p.usuario_id JOIN avaliacoes_profissionais a ON a.profissional_id=p.id WHERE p.ativo=1 GROUP BY p.id HAVING avaliacoes>0 ORDER BY media DESC,avaliacoes DESC LIMIT 5')->fetch_all(MYSQLI_ASSOC);
$feed=$mysqli->query('SELECT pub.*,p.id profissional_id,p.titulo_profissional,u.nome,(SELECT COUNT(*) FROM curtidas_publicacoes c WHERE c.publicacao_id=pub.id) curtidas FROM publicacoes_profissionais pub JOIN profissionais p ON p.id=pub.profissional_id JOIN usuarios u ON u.id=p.usuario_id WHERE pub.ativo=1 AND p.ativo=1 ORDER BY pub.criado_em DESC LIMIT 20')->fetch_all(MYSQLI_ASSOC);
$artigos=$mysqli->query('SELECT id,titulo,conteudo,categoria,criado_em FROM posts_blog WHERE publicado=1 ORDER BY criado_em DESC LIMIT 4')->fetch_all(MYSQLI_ASSOC);
$anuncios=$mysqli->query("SELECT a.*,p.id perfil_id,u.nome FROM anuncios_profissionais a JOIN profissionais p ON p.id=a.profissional_id JOIN usuarios u ON u.id=p.usuario_id WHERE a.status='aprovado' AND (a.inicio_em IS NULL OR a.inicio_em<=NOW()) AND (a.fim_em IS NULL OR a.fim_em>=NOW()) ORDER BY a.criado_em DESC LIMIT 3")->fetch_all(MYSQLI_ASSOC);
require_once __DIR__ . '/includes/header.php';
?>
<div class="container feed-page" id="feed">
<section class="feed-search"><span>ENCONTRE QUEM RESOLVE</span><h1>Serviços, profissionais e ideias para você.</h1><form action="/profissionais.php"><input name="q" placeholder="Qual serviço você procura?"><input name="cidade" placeholder="Cidade"><button>Buscar profissionais</button></form></section>
<div class="feed-layout"><main class="feed-main">
<section><header class="feed-title"><div><span>RECOMENDADOS</span><h2>Profissionais para conhecer</h2></div><a href="/profissionais.php">Ver todos →</a></header><div class="feed-professionals"><?php foreach($recomendados as $pro): ?><article><div class="feed-avatar"><?php echo sanitizar(mb_strtoupper(mb_substr($pro['nome'],0,1))); ?></div><h3><?php echo sanitizar($pro['nome']); ?></h3><p><?php echo sanitizar($pro['titulo_profissional']); ?></p><small>⌖ <?php echo sanitizar($pro['cidade'].'/'.$pro['uf']); ?></small><div class="stars">★ <?php echo $pro['avaliacoes']?number_format($pro['media'],1,',','.'):'Novo'; ?></div><a href="/profissional.php?id=<?php echo (int)$pro['id']; ?>">Ver perfil</a></article><?php endforeach; ?></div></section>
<section><header class="feed-title"><div><span>COMUNIDADE</span><h2>Publicações recentes</h2></div><?php if(usuario_eh_profissional()): ?><a href="/dashboard/publicacoes.php">Criar publicação ＋</a><?php endif; ?></header><?php if($feed): ?><div class="feed-posts"><?php foreach($feed as $post): ?><article><header><div class="feed-avatar"><?php echo sanitizar(mb_strtoupper(mb_substr($post['nome'],0,1))); ?></div><div><a href="/profissional.php?id=<?php echo (int)$post['profissional_id']; ?>"><?php echo sanitizar($post['nome']); ?></a><small><?php echo sanitizar($post['titulo_profissional']); ?> · <?php echo date('d/m/Y H:i',strtotime($post['criado_em'])); ?></small></div></header><p><?php echo nl2br(sanitizar($post['conteudo'])); ?></p><?php if($post['imagem_url']): ?><img src="<?php echo sanitizar($post['imagem_url']); ?>" alt="Imagem da publicação" loading="lazy"><?php endif; ?><div class="post-actions"><form method="POST" action="/feed-acao.php"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="curtir"><input type="hidden" name="publicacao_id" value="<?php echo (int)$post['id']; ?>"><button>♥ <?php echo (int)$post['curtidas']; ?> Curtir</button></form><span>Comentários públicos</span></div><?php $stmt=$mysqli->prepare('SELECT c.comentario,c.criado_em,u.nome FROM comentarios_publicacoes c JOIN usuarios u ON u.id=c.usuario_id WHERE c.publicacao_id=? ORDER BY c.id DESC LIMIT 3');$stmt->bind_param('i',$post['id']);$stmt->execute();$comentarios=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);foreach(array_reverse($comentarios) as $comentario): ?><div class="feed-comment"><strong><?php echo sanitizar($comentario['nome']); ?></strong> <?php echo sanitizar($comentario['comentario']); ?></div><?php endforeach; ?><?php if(usuario_autenticado()): ?><form class="comment-form" method="POST" action="/feed-acao.php"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="comentar"><input type="hidden" name="publicacao_id" value="<?php echo (int)$post['id']; ?>"><input name="comentario" maxlength="1000" placeholder="Escreva um comentário" required><button>Enviar</button></form><?php endif; ?></article><?php endforeach; ?></div><?php else: ?><div class="feed-empty">As primeiras publicações dos profissionais aparecerão aqui.</div><?php endif; ?></section>
<section><header class="feed-title"><div><span>CONTEÚDO</span><h2>Artigos do blog</h2></div><a href="/blog/">Abrir blog →</a></header><div class="feed-articles"><?php foreach($artigos as $artigo): ?><a href="/blog/post.php?id=<?php echo (int)$artigo['id']; ?>"><span><?php echo sanitizar($artigo['categoria']?:'Artigo'); ?></span><h3><?php echo sanitizar($artigo['titulo']); ?></h3><p><?php echo sanitizar(mb_strimwidth(strip_tags($artigo['conteudo']),0,120,'…')); ?></p></a><?php endforeach; ?></div></section>
</main><aside class="feed-sidebar"><section><h2>🏆 Melhor avaliados</h2><?php foreach($ranking as $i=>$pro): ?><a class="rank-item" href="/profissional.php?id=<?php echo (int)$pro['id']; ?>"><b><?php echo $i+1; ?></b><div><strong><?php echo sanitizar($pro['nome']); ?></strong><small>★ <?php echo number_format($pro['media'],1,',','.'); ?> · <?php echo (int)$pro['avaliacoes']; ?> avaliações</small></div></a><?php endforeach; ?><?php if(!$ranking): ?><p>As avaliações dos clientes formarão este ranking.</p><?php endif; ?></section><section class="ad-slot"><small>PUBLICIDADE GOOGLE</small><div>Espaço reservado para Google AdSense</div><span>Configure o identificador ca-pub no painel.</span></section><?php foreach($anuncios as $ad): ?><section class="paid-ad"><small>PATROCINADO</small><?php if($ad['imagem_url']): ?><img src="<?php echo sanitizar($ad['imagem_url']); ?>" alt="Anúncio patrocinado"><?php endif; ?><h3><?php echo sanitizar($ad['titulo']); ?></h3><p><?php echo sanitizar($ad['texto']); ?></p><a href="<?php echo sanitizar($ad['link_url']?:'/profissional.php?id='.(int)$ad['perfil_id']); ?>">Saiba mais →</a></section><?php endforeach; ?></aside></div>
</div>
<script>document.querySelectorAll('.paid-ad').forEach((ad,index)=>{ad.dataset.adSlot='home-sidebar-professional-'+String(index+1).padStart(2,'0');ad.id='ad-slot-'+ad.dataset.adSlot;});<?php if(!$anuncios): ?>const sidebar=document.querySelector('.feed-sidebar');if(sidebar){const panel=document.createElement('section');panel.id='ad-slot-home-sidebar-professional-01';panel.dataset.adSlot='home-sidebar-professional-01';panel.className='paid-ad professional-ad-empty';panel.innerHTML='<small>ANÚNCIOS DE PROFISSIONAIS</small><h3>Divulgue seu trabalho na VoltX</h3><p>Espaço reservado para campanhas criadas pelos profissionais da plataforma.</p><a href="<?php echo usuario_eh_profissional()?'/dashboard/anuncios.php':'/cadastro.php?tipo=profissional'; ?>">Criar anúncio gratuito →</a>';sidebar.append(panel)}<?php endif; ?></script>
<div class="legacy-home" hidden>
<div class="container home-page">
    <section class="home-hero">
        <div class="home-hero-copy"><span class="home-badge"><b>⚡</b> Profissionais e serviços em um só lugar</span><h1>Encontre profissionais.<br><span>Resolva com confiança.</span></h1><p>Busque por especialidade e localização, compare perfis e fale diretamente com quem pode realizar seu serviço.</p><div class="home-actions"><a class="home-whatsapp" href="/profissionais.php"><span>⌕</span> Buscar profissionais</a><a class="home-outline" href="/cadastro.php?tipo=profissional"><span>＋</span> Sou profissional</a></div></div>
        <aside class="home-duty-card"><div class="home-duty-status"><i></i> Novos profissionais podem se cadastrar</div><div class="home-duty-icon">⚡</div><h2>Ofereça seus serviços</h2><p>Crie um perfil público, informe sua região e publique suas próprias ofertas.</p><div class="home-duty-hours"><span>⌖</span><div><small>Área inicial da plataforma</small><strong><?php echo sanitizar($regiao); ?></strong></div></div></aside>
    </section>
    <section class="home-stats" aria-label="Diferenciais da VoltX"><div><strong><?php echo $total_profissionais; ?></strong><span>Profissionais publicados</span></div><div><strong><?php echo count($servicos_home); ?></strong><span>Soluções VoltX</span></div><div><strong>Busca</strong><span>Por categoria e cidade</span></div><div><strong>Direto</strong><span>Contato com o profissional</span></div></section>
    <section class="home-services">
        <header class="home-section-heading"><div><span>NOSSAS ESPECIALIDADES</span><h2>Nossas soluções elétricas</h2></div><p>Serviços planejados e executados com transparência e valores médios claros.</p></header>
        <?php if ($servicos_home): ?><div class="home-services-grid"><?php foreach (array_slice($servicos_home, 0, 6) as $servico): $descricao=trim($servico['descricao'] ?? ''); $destino='/agendar.php?servico_id='.(int)$servico['id']; $link_agendar=usuario_autenticado() ? $destino : '/cadastro.php?redirect='.rawurlencode($destino); ?><article class="home-service-card"><div><span class="home-service-icon">⚡</span><h3><?php echo sanitizar($servico['nome']); ?></h3><p><?php echo sanitizar(mb_strimwidth($descricao,0,145,'…')); ?></p><strong class="home-service-price">A partir de R$ <?php echo number_format($servico['preco'],2,',','.'); ?></strong></div><a href="<?php echo sanitizar($link_agendar); ?>">Agendar agora <span>→</span></a></article><?php endforeach; ?></div><a class="home-all-services" href="/servicos.php">Ver todos os serviços <span>→</span></a><?php else: ?><div class="home-empty"><span>⚡</span><h3>Novos serviços em breve</h3><p>Enquanto isso, fale diretamente com nossa equipe.</p></div><?php endif; ?>
    </section>
    <section class="home-callout"><div><span>ATENDIMENTO DIRETO</span><h2>Precisa de um orçamento personalizado?</h2><p>Envie uma foto ou vídeo do problema pelo WhatsApp e receba uma orientação inicial, sem compromisso.</p></div><a class="home-whatsapp" href="https://wa.me/<?php echo $whatsapp; ?>?text=<?php echo $mensagem_whatsapp; ?>" target="_blank" rel="noopener noreferrer"><span>◉</span> Falar com a VoltX</a></section>
</div>
</div><?php require_once __DIR__ . '/includes/footer.php'; ?>
