<?php
$titulo_pagina = 'Encontrar profissionais';
$estilos_pagina = ['/assets/css/marketplace.css?v=1','/assets/css/chat-contact.css?v=1'];
require_once __DIR__ . '/includes/functions.php';
$busca=trim($_GET['q'] ?? ''); $categoria=trim($_GET['categoria'] ?? ''); $cidade=trim($_GET['cidade'] ?? ''); $online=!empty($_GET['online']);
$sql="SELECT p.*,u.nome,u.telefone,COUNT(o.id) total_ofertas,MIN(o.preco_inicial) menor_preco FROM profissionais p JOIN usuarios u ON u.id=p.usuario_id LEFT JOIN ofertas_profissionais o ON o.profissional_id=p.id AND o.ativo=1 WHERE p.ativo=1 AND (?='' OR u.nome LIKE CONCAT('%',?,'%') OR p.titulo_profissional LIKE CONCAT('%',?,'%') OR p.bio LIKE CONCAT('%',?,'%')) AND (?='' OR p.categoria_principal=?) AND (?='' OR p.cidade LIKE CONCAT('%',?,'%')) AND (?=0 OR p.atende_online=1) GROUP BY p.id ORDER BY p.verificado DESC,total_ofertas DESC,p.atualizado_em DESC";
$stmt=$mysqli->prepare($sql); $online_int=$online?1:0; $stmt->bind_param('ssssssssi',$busca,$busca,$busca,$busca,$categoria,$categoria,$cidade,$cidade,$online_int); $stmt->execute(); $profissionais=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$categorias=$mysqli->query("SELECT DISTINCT categoria_principal FROM profissionais WHERE ativo=1 AND categoria_principal<>'' ORDER BY categoria_principal")->fetch_all(MYSQLI_ASSOC);
require_once __DIR__ . '/includes/header.php';
?>
<section class="market-page"><div class="container"><header class="market-heading"><span>MARKETPLACE VOLTX</span><h1>Encontre o profissional certo</h1><p>Compare especialidades, localização e serviços antes de entrar em contato.</p></header>
<form class="market-filters" method="GET"><div><label for="q">O que você precisa?</label><input id="q" name="q" value="<?php echo sanitizar($busca); ?>" placeholder="Ex.: eletricista, pintura, instalação"></div><div><label for="categoria">Categoria</label><select id="categoria" name="categoria"><option value="">Todas</option><?php foreach($categorias as $item): ?><option <?php echo $categoria===$item['categoria_principal']?'selected':''; ?>><?php echo sanitizar($item['categoria_principal']); ?></option><?php endforeach; ?></select></div><div><label for="cidade">Cidade</label><input id="cidade" name="cidade" value="<?php echo sanitizar($cidade); ?>" placeholder="Sua cidade"></div><label class="online-filter"><input type="checkbox" name="online" value="1" <?php echo $online?'checked':''; ?>> Atendimento online</label><button type="submit">Buscar profissionais</button></form>
<div class="market-result"><strong><?php echo count($profissionais); ?></strong> profissional(is) encontrado(s)</div>
<?php if($profissionais): ?><div class="professionals-grid"><?php foreach($profissionais as $profissional): ?><article class="professional-card"><div class="professional-top"><div class="professional-avatar"><?php if($profissional['foto_url']): ?><img src="<?php echo sanitizar($profissional['foto_url']); ?>" alt="Foto de <?php echo sanitizar($profissional['nome']); ?>"><?php else: ?><?php echo sanitizar(mb_strtoupper(mb_substr($profissional['nome'],0,1))); ?><?php endif; ?></div><div><div class="professional-name"><h2><?php echo sanitizar($profissional['nome']); ?></h2><?php if($profissional['verificado']): ?><span title="Perfil verificado">✓</span><?php endif; ?></div><p><?php echo sanitizar($profissional['titulo_profissional']); ?></p></div></div><div class="professional-tags"><span><?php echo sanitizar($profissional['categoria_principal']); ?></span><span>⌖ <?php echo sanitizar($profissional['cidade'].'/'.$profissional['uf']); ?></span><?php if($profissional['atende_online']): ?><span>Online</span><?php endif; ?></div><p class="professional-bio"><?php echo sanitizar(mb_strimwidth($profissional['bio'] ?? '',0,155,'…')); ?></p><div class="professional-meta"><span><strong><?php echo (int)$profissional['total_ofertas']; ?></strong> serviços</span><?php if($profissional['menor_preco']!==null): ?><span>a partir de <strong>R$ <?php echo number_format($profissional['menor_preco'],2,',','.'); ?></strong></span><?php endif; ?></div><a href="/profissional.php?id=<?php echo (int)$profissional['id']; ?>">Ver perfil e serviços →</a></article><?php endforeach; ?></div><?php else: ?><div class="market-empty"><span>⌕</span><h2>Nenhum profissional encontrado</h2><p>Tente remover algum filtro ou buscar por outra especialidade.</p></div><?php endif; ?>
</div></section>
<script>document.querySelectorAll('.professional-card').forEach(card=>{const profile=card.querySelector('a[href*="profissional.php?id="]');if(!profile)return;const id=new URL(profile.href).searchParams.get('id'),destination='/chat.php?profissional_id='+id,chat=document.createElement('a');chat.className='card-chat-button';chat.textContent='✉ Conversar pelo chat';chat.href=<?php echo usuario_autenticado() ? 'destination' : "'/login.php?redirect='+encodeURIComponent(destination)"; ?>;card.insertBefore(chat,profile)});</script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
