<?php
$titulo_pagina='Meus Anúncios';$estilos_pagina=['/assets/css/admin.css?v=6','/assets/css/creator-dashboard.css?v=1','/assets/css/professional-ads.css?v=2'];$scripts_pagina=['/assets/js/professional-ads-form.js?v=1'];require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/functions.php';verificarProfissional();$perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']);if(!$perfil)redirecionar('/dashboard/profissional.php');$erros=[];
function salvar_foto_anuncio($arquivo,&$erros){if(empty($arquivo['name'])){$erros[]='A foto do anúncio é obrigatória.';return '';}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($arquivo['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($ext[$mime])){$erros[]='Envie uma foto JPG, PNG ou WebP.';return '';}$dir=__DIR__.'/../assets/uploads/ads';if(!is_dir($dir))mkdir($dir,0755,true);$nome=bin2hex(random_bytes(16)).'.'.$ext[$mime];if(!move_uploaded_file($arquivo['tmp_name'],$dir.'/'.$nome)){$erros[]='Não foi possível salvar a foto.';return '';}return '/assets/uploads/ads/'.$nome;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validar_csrf($_POST['csrf_token']??''))$erros[]='A sessão expirou.';$acao=$_POST['acao']??'criar';$id=(int)($_POST['id']??0);
 if(!$erros&&in_array($acao,['encerrar','excluir'],true)){$sql=$acao==='excluir'?'DELETE FROM anuncios_profissionais WHERE id=? AND profissional_id=?':"UPDATE anuncios_profissionais SET status='encerrado' WHERE id=? AND profissional_id=?";$stmt=$mysqli->prepare($sql);$stmt->bind_param('ii',$id,$perfil['id']);$stmt->execute();mensagem_sucesso($acao==='excluir'?'Anúncio excluído.':'Campanha encerrada.');redirecionar('/dashboard/anuncios.php');}
 if($acao==='criar'){$categoria=normalizar_rotulo($_POST['categoria']??'');$nome=normalizar_rotulo($_POST['nome']??'');$descricao=trim($_POST['descricao']??'');$link=normalizar_url_publicitaria($_POST['link_url']??'');$duracao=(int)($_POST['duracao_segundos']??10);$imagem=salvar_foto_anuncio($_FILES['foto']??[],$erros);if(mb_strlen($categoria)<2)$erros[]='Selecione uma categoria.';if(mb_strlen($nome)<3)$erros[]='Informe o nome do anúncio.';if(mb_strlen($descricao)<10)$erros[]='A descrição deve ter ao menos 10 caracteres.';if($link===false)$erros[]='Informe um domínio válido, como narrativas.site.';if($duracao<5||$duracao>20)$erros[]='O tempo de exposição deve ficar entre 5 e 20 segundos.';if(!$erros){$stmt=$mysqli->prepare("INSERT INTO anuncios_profissionais(profissional_id,categoria,titulo,texto,imagem_url,link_url,duracao_segundos,status) VALUES(?,?,?,?,?,?,?,'aprovado')");$stmt->bind_param('isssssi',$perfil['id'],$categoria,$nome,$descricao,$imagem,$link,$duracao);$stmt->execute();$id_anuncio=$mysqli->insert_id;$codigo='VXAD-'.str_pad((string)$id_anuncio,8,'0',STR_PAD_LEFT);$stmt=$mysqli->prepare('UPDATE anuncios_profissionais SET codigo=? WHERE id=?');$stmt->bind_param('si',$codigo,$id_anuncio);$stmt->execute();mensagem_sucesso('Anúncio publicado gratuitamente. Código: '.$codigo);redirecionar('/dashboard/anuncios.php');}}
}
$stmt=$mysqli->prepare('SELECT nome FROM categorias_profissionais WHERE profissional_id=? ORDER BY nome');$stmt->bind_param('i',$perfil['id']);$stmt->execute();$categorias=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt=$mysqli->prepare('SELECT * FROM anuncios_profissionais WHERE profissional_id=? ORDER BY criado_em DESC');$stmt->bind_param('i',$perfil['id']);$stmt->execute();$anuncios=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);require_once __DIR__.'/../includes/header.php';
?>
<div class="container professional-ads-page"><div class="page-heading"><div><span class="profile-kicker">DIVULGAÇÃO PROFISSIONAL</span><h1>Meus Anúncios</h1><p>Crie campanhas para os espaços patrocinados da VoltX.</p></div></div><?php exibir_mensagens(); ?><?php if($erros): ?><div class="alerta alerta-erro"><?php echo sanitizar(implode(' ',$erros)); ?></div><?php endif; ?><section class="free-phase"><strong>Fase gratuita</strong><span>Os anúncios são publicados imediatamente. Futuramente este poderá ser um recurso pago.</span></section>
<form class="ad-create-form" method="POST" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="criar"><h2>Criar anúncio</h2><div class="form-grid"><div class="form-group"><label for="categoria">Categoria</label><select id="categoria" name="categoria" required><option value="">Selecione</option><option>Geral</option><?php foreach($categorias as $cat): ?><option><?php echo sanitizar($cat['nome']); ?></option><?php endforeach; ?></select></div><div class="form-group"><label for="nome">Nome do anúncio</label><input id="nome" name="nome" maxlength="180" required></div><div class="form-group form-span"><label for="descricao">Descrição</label><textarea id="descricao" name="descricao" rows="4" maxlength="500" required></textarea></div><div class="form-group"><label for="foto">Foto</label><input id="foto" name="foto" type="file" accept="image/jpeg,image/png,image/webp" required></div><div class="form-group"><label for="link_url">Link de destino (opcional)</label><input id="link_url" name="link_url" type="url" placeholder="https://..."></div></div><button class="btn" type="submit">Publicar anúncio gratuito</button></form>
<section class="my-ad-list"><h2>Campanhas criadas</h2><?php if($anuncios): ?><div class="my-ad-grid"><?php foreach($anuncios as $ad): ?><article><img src="<?php echo sanitizar($ad['imagem_url']); ?>" alt=""><div><span><?php echo sanitizar($ad['categoria']); ?></span><h3><?php echo sanitizar($ad['titulo']); ?></h3><p><?php echo sanitizar($ad['texto']); ?></p><code><?php echo sanitizar($ad['codigo']); ?></code><small class="status <?php echo $ad['status']==='aprovado'?'status-confirmado':'status-cancelado'; ?>"><?php echo $ad['status']==='aprovado'?'Publicado':'Encerrado'; ?></small><div class="table-actions"><?php if($ad['status']==='aprovado'): ?><form method="POST"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="encerrar"><input type="hidden" name="id" value="<?php echo (int)$ad['id']; ?>"><button class="btn-small">Encerrar</button></form><?php endif; ?><form method="POST" onsubmit="return confirm('Excluir este anúncio?')"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="excluir"><input type="hidden" name="id" value="<?php echo (int)$ad['id']; ?>"><button class="btn-small btn-danger">Excluir</button></form></div></div></article><?php endforeach; ?></div><?php else: ?><p>Você ainda não criou anúncios.</p><?php endif; ?></section></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
