<?php
$titulo_pagina='Meus Serviços'; $estilos_pagina=['/assets/css/admin.css?v=5']; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/functions.php'; verificarProfissional(); $perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']);
if(!$perfil){mensagem_erro('Complete seu perfil profissional antes de cadastrar serviços.');redirecionar('/dashboard/profissional.php');}$erros=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validar_csrf($_POST['csrf_token']??''))$erros[]='A sessão expirou.';$acao=$_POST['acao']??'criar';
 if(!$erros&&in_array($acao,['alternar','excluir'],true)){$id=(int)($_POST['id']??0);$sql=$acao==='excluir'?'DELETE FROM ofertas_profissionais WHERE id=? AND profissional_id=?':'UPDATE ofertas_profissionais SET ativo=NOT ativo WHERE id=? AND profissional_id=?';$stmt=$mysqli->prepare($sql);$stmt->bind_param('ii',$id,$perfil['id']);$stmt->execute();mensagem_sucesso($acao==='excluir'?'Serviço removido.':'Disponibilidade atualizada.');redirecionar('/dashboard/ofertas.php');}
 if($acao==='criar'){$nome=trim($_POST['nome']??'');$categoria=trim($_POST['categoria']??'');$descricao=trim($_POST['descricao']??'');$preco=str_replace(',','.',trim($_POST['preco_inicial']??''));$unidade=trim($_POST['unidade_preco']??'por serviço');if(mb_strlen($nome)<3||!$categoria||mb_strlen($descricao)<10)$erros[]='Preencha nome, categoria e uma descrição detalhada.';if($preco!==''&&(!is_numeric($preco)||$preco<0))$erros[]='Informe um preço inicial válido.';if(!$erros){$preco_valor=$preco===''?null:(float)$preco;$stmt=$mysqli->prepare('INSERT INTO ofertas_profissionais(profissional_id,nome,categoria,descricao,preco_inicial,unidade_preco) VALUES(?,?,?,?,?,?)');$stmt->bind_param('isssds',$perfil['id'],$nome,$categoria,$descricao,$preco_valor,$unidade);$stmt->execute();mensagem_sucesso('Serviço publicado no seu perfil.');redirecionar('/dashboard/ofertas.php');}}
}
$stmt=$mysqli->prepare('SELECT * FROM ofertas_profissionais WHERE profissional_id=? ORDER BY criado_em DESC');$stmt->bind_param('i',$perfil['id']);$stmt->execute();$ofertas=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);require_once __DIR__.'/../includes/header.php';
?>
<div class="container"><div class="page-heading"><div><h1>Meus Serviços</h1><p>Cadastre as soluções que os clientes encontrarão no seu perfil.</p></div></div><?php exibir_mensagens(); ?><?php if($erros): ?><div class="alerta alerta-erro"><?php echo sanitizar(implode(' ',$erros)); ?></div><?php endif; ?><form method="POST" class="service-form"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="criar"><div class="form-grid"><div class="form-group"><label for="nome">Nome do serviço</label><input id="nome" name="nome" required></div><div class="form-group"><label for="categoria">Categoria</label><input id="categoria" name="categoria" required></div><div class="form-group form-span"><label for="descricao">Descrição</label><textarea id="descricao" name="descricao" rows="4" required></textarea></div><div class="form-group"><label for="preco_inicial">Preço inicial (opcional)</label><input id="preco_inicial" name="preco_inicial" inputmode="decimal" placeholder="150,00"></div><div class="form-group"><label for="unidade_preco">Forma de cobrança</label><select id="unidade_preco" name="unidade_preco"><option>por serviço</option><option>por hora</option><option>por diária</option><option>por projeto</option></select></div></div><button class="btn" type="submit">Publicar serviço</button></form><div class="dashboard-menu"><?php foreach($ofertas as $oferta): ?><article class="card"><h3><?php echo sanitizar($oferta['nome']); ?></h3><p><?php echo sanitizar($oferta['categoria']); ?> · <?php echo $oferta['preco_inicial']!==null?'R$ '.number_format($oferta['preco_inicial'],2,',','.'):'Sob consulta'; ?></p><span class="status <?php echo $oferta['ativo']?'status-confirmado':'status-cancelado'; ?>"><?php echo $oferta['ativo']?'Publicado':'Pausado'; ?></span><div class="table-actions"><form method="POST"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="alternar"><input type="hidden" name="id" value="<?php echo (int)$oferta['id']; ?>"><button class="btn-small" type="submit"><?php echo $oferta['ativo']?'Pausar':'Publicar'; ?></button></form><form method="POST" onsubmit="return confirm('Remover este serviço?')"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><input type="hidden" name="acao" value="excluir"><input type="hidden" name="id" value="<?php echo (int)$oferta['id']; ?>"><button class="btn-small btn-danger" type="submit">Excluir</button></form></div></article><?php endforeach; ?></div></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
