<?php
$titulo_pagina='Meu Perfil Profissional'; $estilos_pagina=['/assets/css/admin.css?v=5','/assets/css/marketplace.css?v=1']; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/functions.php'; verificarProfissional();
$perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']); $erros=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validar_csrf($_POST['csrf_token']??''))$erros[]='A sessão expirou. Atualize a página.';
 $titulo=trim($_POST['titulo_profissional']??'');$bio=trim($_POST['bio']??'');$categoria=trim($_POST['categoria_principal']??'');$cidade=trim($_POST['cidade']??'');$uf=mb_strtoupper(trim($_POST['uf']??''));$foto=trim($_POST['foto_url']??'');$online=!empty($_POST['atende_online'])?1:0;
 if(mb_strlen($titulo)<3)$erros[]='Informe seu título profissional.'; if(mb_strlen($bio)<20)$erros[]='Escreva uma apresentação com pelo menos 20 caracteres.'; if(!$categoria||!$cidade||!preg_match('/^[A-Z]{2}$/',$uf))$erros[]='Preencha categoria, cidade e UF corretamente.'; if($foto&&!filter_var($foto,FILTER_VALIDATE_URL))$erros[]='Informe uma URL de foto válida.';
 if(!$erros){$stmt=$mysqli->prepare('INSERT INTO profissionais(usuario_id,titulo_profissional,bio,categoria_principal,cidade,uf,foto_url,atende_online) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE titulo_profissional=VALUES(titulo_profissional),bio=VALUES(bio),categoria_principal=VALUES(categoria_principal),cidade=VALUES(cidade),uf=VALUES(uf),foto_url=VALUES(foto_url),atende_online=VALUES(atende_online)');$stmt->bind_param('issssssi',$_SESSION['usuario_id'],$titulo,$bio,$categoria,$cidade,$uf,$foto,$online);$stmt->execute();mensagem_sucesso('Perfil profissional atualizado e publicado.');redirecionar('/dashboard/profissional.php');}
}
$perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']); require_once __DIR__.'/../includes/header.php';
?>
<div class="container"><div class="page-heading"><div><h1>Meu Perfil Profissional</h1><p>Estas informações serão exibidas para clientes na busca.</p></div><?php if($perfil): ?><a class="btn btn-secondary" href="/profissional.php?id=<?php echo (int)$perfil['id']; ?>">Ver perfil público</a><?php endif; ?></div><?php exibir_mensagens(); ?><?php if($erros): ?><div class="alerta alerta-erro"><ul><?php foreach($erros as $erro): ?><li><?php echo sanitizar($erro); ?></li><?php endforeach; ?></ul></div><?php endif; ?><form method="POST" class="form-container"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><div class="form-group"><label for="titulo_profissional">Título profissional</label><input id="titulo_profissional" name="titulo_profissional" placeholder="Ex.: Eletricista residencial e predial" value="<?php echo sanitizar($_POST['titulo_profissional']??$perfil['titulo_profissional']??''); ?>" required></div><div class="form-group"><label for="categoria_principal">Categoria principal</label><input id="categoria_principal" name="categoria_principal" placeholder="Ex.: Elétrica" value="<?php echo sanitizar($_POST['categoria_principal']??$perfil['categoria_principal']??''); ?>" required></div><div class="form-group"><label for="bio">Sobre seu trabalho</label><textarea id="bio" name="bio" rows="7" placeholder="Conte sua experiência, especialidades e diferenciais." required><?php echo sanitizar($_POST['bio']??$perfil['bio']??''); ?></textarea></div><div class="form-grid"><div class="form-group"><label for="cidade">Cidade</label><input id="cidade" name="cidade" value="<?php echo sanitizar($_POST['cidade']??$perfil['cidade']??''); ?>" required></div><div class="form-group"><label for="uf">UF</label><input id="uf" name="uf" maxlength="2" value="<?php echo sanitizar($_POST['uf']??$perfil['uf']??''); ?>" required></div></div><div class="form-group"><label for="foto_url">URL da foto profissional</label><input id="foto_url" name="foto_url" type="url" value="<?php echo sanitizar($_POST['foto_url']??$perfil['foto_url']??''); ?>" placeholder="https://..."></div><label class="toggle-field"><input type="checkbox" name="atende_online" value="1" <?php echo !empty($_POST['atende_online'])||(!$_POST&& !empty($perfil['atende_online']))?'checked':''; ?>> Também realizo atendimento online</label><button class="btn" type="submit">Salvar e publicar perfil</button></form></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
