<?php
$titulo_pagina='Meu Perfil Profissional';$estilos_pagina=['/assets/css/admin.css?v=6','/assets/css/marketplace.css?v=2'];require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/functions.php';verificarProfissional();
$perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']);$erros=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!validar_csrf($_POST['csrf_token']??''))$erros[]='A sessão expirou. Atualize a página.';
 $titulo=trim($_POST['titulo_profissional']??'');$bio=trim($_POST['bio']??'');$categoria=trim($_POST['categoria_principal']??'');$cidade=normalizar_nome($_POST['cidade']??'');$uf=mb_strtoupper(trim($_POST['uf']??''));$foto=trim($_POST['foto_url']??'');$online=!empty($_POST['atende_online'])?1:0;$mei=!empty($_POST['mei'])?1:0;$marca=trim($_POST['marca']??'');$cnpj=mb_strtoupper(preg_replace('/[^A-Z0-9]/i','',$_POST['cnpj']??''));
 if(mb_strlen($titulo)<3)$erros[]='Informe seu título profissional.';if(mb_strlen($bio)<20)$erros[]='Escreva uma apresentação com pelo menos 20 caracteres.';if(!$categoria||!$cidade||!preg_match('/^[A-Z]{2}$/',$uf))$erros[]='Preencha categoria, cidade e UF corretamente.';if($foto&&!filter_var($foto,FILTER_VALIDATE_URL))$erros[]='Informe uma URL de foto válida.';
 if($mei){if(mb_strlen($marca)<2)$erros[]='Informe a marca usada pelo seu MEI.';if(!validar_cnpj($cnpj))$erros[]='O CNPJ informado não passou na validação dos dígitos verificadores.';}else{$marca='';$cnpj='';}
 if(!$erros&&$mei){$id=(int)($perfil['id']??0);$stmt=$mysqli->prepare('SELECT id FROM profissionais WHERE (LOWER(marca)=LOWER(?) OR cnpj=?) AND id<>? LIMIT 1');$stmt->bind_param('ssi',$marca,$cnpj,$id);$stmt->execute();if($stmt->get_result()->fetch_assoc())$erros[]='Esta marca ou CNPJ já está vinculado a outro perfil profissional.';$stmt=$mysqli->prepare('SELECT id FROM empresas WHERE cnpj=? LIMIT 1');$stmt->bind_param('s',$cnpj);$stmt->execute();if($stmt->get_result()->fetch_assoc())$erros[]='Este CNPJ já pertence a uma conta empresarial.';}
 if(!$erros){$marca_db=$marca?:null;$cnpj_db=$cnpj?:null;$stmt=$mysqli->prepare('INSERT INTO profissionais(usuario_id,titulo_profissional,bio,marca,mei,cnpj,categoria_principal,cidade,uf,foto_url,atende_online) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE titulo_profissional=VALUES(titulo_profissional),bio=VALUES(bio),marca=VALUES(marca),mei=VALUES(mei),cnpj=VALUES(cnpj),categoria_principal=VALUES(categoria_principal),cidade=VALUES(cidade),uf=VALUES(uf),foto_url=VALUES(foto_url),atende_online=VALUES(atende_online)');$stmt->bind_param('isssisssssi',$_SESSION['usuario_id'],$titulo,$bio,$marca_db,$mei,$cnpj_db,$categoria,$cidade,$uf,$foto,$online);$stmt->execute();mensagem_sucesso('Perfil profissional atualizado e publicado.');redirecionar('/dashboard/profissional.php');}
}
$perfil=pegar_perfil_profissional_por_usuario($_SESSION['usuario_id']);require_once __DIR__.'/../includes/header.php';
?>
<div class="container"><div class="page-heading"><div><h1>Meu Perfil Profissional</h1><p>Estas informações serão exibidas para clientes na busca.</p></div><?php if($perfil): ?><a class="btn btn-secondary" href="/profissional.php?id=<?php echo (int)$perfil['id']; ?>">Ver perfil público</a><?php endif; ?></div><?php exibir_mensagens(); ?><?php if($erros): ?><div class="alerta alerta-erro"><ul><?php foreach($erros as $erro): ?><li><?php echo sanitizar($erro); ?></li><?php endforeach; ?></ul></div><?php endif; ?>
<form method="POST" class="form-container"><input type="hidden" name="csrf_token" value="<?php echo token_csrf(); ?>"><div class="form-grid"><div class="form-group"><label>Título profissional</label><input name="titulo_profissional" value="<?php echo sanitizar($_POST['titulo_profissional']??$perfil['titulo_profissional']??''); ?>" required></div><div class="form-group"><label>Categoria principal</label><input name="categoria_principal" value="<?php echo sanitizar($_POST['categoria_principal']??$perfil['categoria_principal']??''); ?>" required></div><div class="form-group form-span"><label>Sobre seu trabalho</label><textarea name="bio" rows="7" required><?php echo sanitizar($_POST['bio']??$perfil['bio']??''); ?></textarea></div><div class="form-group"><label>Cidade</label><input name="cidade" value="<?php echo sanitizar($_POST['cidade']??$perfil['cidade']??''); ?>" required></div><div class="form-group"><label>UF</label><input name="uf" maxlength="2" value="<?php echo sanitizar($_POST['uf']??$perfil['uf']??''); ?>" required></div><div class="form-group form-span"><label>URL da foto profissional</label><input name="foto_url" type="url" value="<?php echo sanitizar($_POST['foto_url']??$perfil['foto_url']??''); ?>"></div></div>
<fieldset class="form-section"><legend>Identidade MEI (opcional)</legend><label class="toggle-field"><input type="checkbox" name="mei" value="1" <?php echo !empty($_POST['mei'])||(!$_POST&&!empty($perfil['mei']))?'checked':''; ?>> Trabalho como MEI e quero exibir minha marca</label><div class="form-grid"><div class="form-group"><label>Marca da empresa (única na VoltX)</label><input name="marca" value="<?php echo sanitizar($_POST['marca']??$perfil['marca']??''); ?>"></div><div class="form-group"><label>CNPJ do MEI</label><input name="cnpj" maxlength="18" value="<?php echo sanitizar($_POST['cnpj']??$perfil['cnpj']??''); ?>"><small>A validação confirma o formato, não a situação cadastral na Receita Federal.</small></div></div></fieldset><label class="toggle-field"><input type="checkbox" name="atende_online" value="1" <?php echo !empty($_POST['atende_online'])||(!$_POST&&!empty($perfil['atende_online']))?'checked':''; ?>> Também realizo atendimento online</label><button class="btn" type="submit">Salvar e publicar perfil</button></form></div><?php require_once __DIR__.'/../includes/footer.php'; ?>
